-- =========================================================================
-- SENDUU — Taxonomie catégories/sous-catégories réelle (13 catégories,
-- ~100 sous-catégories). Idempotent via ON CONFLICT (slug) : peut être
-- rejoué sans créer de doublons. "Offres & Promotions" est une catégorie
-- vitrine sans sous-catégorie physique — ses "sous-rubriques" (Flash
-- Deals, Nouveautés...) sont des collections dynamiques pilotées par les
-- flags produit (is_flash_deal, is_new...), pas de fausses catégories.
-- =========================================================================

insert into categories (name, slug, sort_order, is_active, is_visible) values
  ('Téléphones & High-Tech', 'telephones-high-tech', 1, true, true),
  ('Informatique', 'informatique', 2, true, true),
  ('Maison & Cuisine', 'maison-cuisine', 3, true, true),
  ('Mode & Accessoires', 'mode-accessoires', 4, true, true),
  ('Beauté & Soins', 'beaute-soins', 5, true, true),
  ('Bébé & Enfants', 'bebe-enfants', 6, true, true),
  ('Sport & Loisirs', 'sport-loisirs', 7, true, true),
  ('Auto & Moto', 'auto-moto', 8, true, true),
  ('Énergie & Solaire', 'energie-solaire', 9, true, true),
  ('Sécurité & Surveillance', 'securite-surveillance', 10, true, true),
  ('Gaming', 'gaming', 11, true, true),
  ('Bricolage & Outils', 'bricolage-outils', 12, true, true),
  ('Offres & Promotions', 'offres-promotions', 13, true, true)
on conflict (slug) do update set name = excluded.name, sort_order = excluded.sort_order, is_active = true, is_visible = true;

insert into subcategories (name, slug, category_id, sort_order, is_active, is_visible) values
  ('Smartphones', 'smartphones', (select id from categories where slug = 'telephones-high-tech'), 1, true, true),
  ('Téléphones reconditionnés', 'telephones-reconditionnes', (select id from categories where slug = 'telephones-high-tech'), 2, true, true),
  ('Accessoires téléphone', 'accessoires-telephone', (select id from categories where slug = 'telephones-high-tech'), 3, true, true),
  ('Écouteurs & Casques', 'ecouteurs-casques', (select id from categories where slug = 'telephones-high-tech'), 4, true, true),
  ('Enceintes Bluetooth', 'enceintes-bluetooth', (select id from categories where slug = 'telephones-high-tech'), 5, true, true),
  ('Montres connectées', 'montres-connectees', (select id from categories where slug = 'telephones-high-tech'), 6, true, true),
  ('Chargeurs & Câbles', 'chargeurs-cables', (select id from categories where slug = 'telephones-high-tech'), 7, true, true),
  ('Power Banks', 'power-banks', (select id from categories where slug = 'telephones-high-tech'), 8, true, true),
  ('Supports téléphone', 'supports-telephone', (select id from categories where slug = 'telephones-high-tech'), 9, true, true),
  ('Gadgets électroniques', 'gadgets-electroniques', (select id from categories where slug = 'telephones-high-tech'), 10, true, true),
  ('Ordinateurs portables', 'ordinateurs-portables', (select id from categories where slug = 'informatique'), 1, true, true),
  ('PC 2-en-1', 'pc-2-en-1', (select id from categories where slug = 'informatique'), 2, true, true),
  ('Ordinateurs de bureau', 'ordinateurs-de-bureau', (select id from categories where slug = 'informatique'), 3, true, true),
  ('Tablettes', 'tablettes', (select id from categories where slug = 'informatique'), 4, true, true),
  ('Claviers & Souris', 'claviers-souris', (select id from categories where slug = 'informatique'), 5, true, true),
  ('SSD / HDD / Stockage', 'ssd-hdd-stockage', (select id from categories where slug = 'informatique'), 6, true, true),
  ('Clés USB', 'cles-usb', (select id from categories where slug = 'informatique'), 7, true, true),
  ('Adaptateurs & Hub USB', 'adaptateurs-hub-usb', (select id from categories where slug = 'informatique'), 8, true, true),
  ('Accessoires PC', 'accessoires-pc', (select id from categories where slug = 'informatique'), 9, true, true),
  ('Réseaux & Wi-Fi', 'reseaux-wi-fi', (select id from categories where slug = 'informatique'), 10, true, true),
  ('Imprimantes & Consommables', 'imprimantes-consommables', (select id from categories where slug = 'informatique'), 11, true, true),
  ('Rangement & Organisation', 'rangement-organisation', (select id from categories where slug = 'maison-cuisine'), 1, true, true),
  ('Cuisine', 'cuisine', (select id from categories where slug = 'maison-cuisine'), 2, true, true),
  ('Ustensiles de cuisine', 'ustensiles-de-cuisine', (select id from categories where slug = 'maison-cuisine'), 3, true, true),
  ('Éclairage', 'eclairage', (select id from categories where slug = 'maison-cuisine'), 4, true, true),
  ('Décoration', 'decoration', (select id from categories where slug = 'maison-cuisine'), 5, true, true),
  ('Nettoyage & Entretien', 'nettoyage-entretien', (select id from categories where slug = 'maison-cuisine'), 6, true, true),
  ('Salle de bain', 'salle-de-bain', (select id from categories where slug = 'maison-cuisine'), 7, true, true),
  ('Articles pour la maison', 'articles-pour-la-maison', (select id from categories where slug = 'maison-cuisine'), 8, true, true),
  ('Gadgets maison', 'gadgets-maison', (select id from categories where slug = 'maison-cuisine'), 9, true, true),
  ('Réfrigérateurs', 'refrigerateurs', (select id from categories where slug = 'maison-cuisine'), 10, true, true),
  ('Vêtements Homme', 'vetements-homme', (select id from categories where slug = 'mode-accessoires'), 1, true, true),
  ('Vêtements Femme', 'vetements-femme', (select id from categories where slug = 'mode-accessoires'), 2, true, true),
  ('Chaussures', 'chaussures', (select id from categories where slug = 'mode-accessoires'), 3, true, true),
  ('Sacs', 'sacs', (select id from categories where slug = 'mode-accessoires'), 4, true, true),
  ('Montres', 'montres', (select id from categories where slug = 'mode-accessoires'), 5, true, true),
  ('Bijoux & Accessoires', 'bijoux-accessoires', (select id from categories where slug = 'mode-accessoires'), 6, true, true),
  ('Lunettes', 'lunettes', (select id from categories where slug = 'mode-accessoires'), 7, true, true),
  ('Accessoires de mode', 'accessoires-de-mode', (select id from categories where slug = 'mode-accessoires'), 8, true, true),
  ('Soins du visage', 'soins-du-visage', (select id from categories where slug = 'beaute-soins'), 1, true, true),
  ('Soins du corps', 'soins-du-corps', (select id from categories where slug = 'beaute-soins'), 2, true, true),
  ('Accessoires beauté', 'accessoires-beaute', (select id from categories where slug = 'beaute-soins'), 3, true, true),
  ('Coiffure', 'coiffure', (select id from categories where slug = 'beaute-soins'), 4, true, true),
  ('Manucure & Pédicure', 'manucure-pedicure', (select id from categories where slug = 'beaute-soins'), 5, true, true),
  ('Parfums', 'parfums', (select id from categories where slug = 'beaute-soins'), 6, true, true),
  ('Miroirs & Accessoires', 'miroirs-accessoires', (select id from categories where slug = 'beaute-soins'), 7, true, true),
  ('Vêtements bébé', 'vetements-bebe', (select id from categories where slug = 'bebe-enfants'), 1, true, true),
  ('Chaussures enfants', 'chaussures-enfants', (select id from categories where slug = 'bebe-enfants'), 2, true, true),
  ('Jouets', 'jouets', (select id from categories where slug = 'bebe-enfants'), 3, true, true),
  ('Éveil & Éducation', 'eveil-education', (select id from categories where slug = 'bebe-enfants'), 4, true, true),
  ('Accessoires bébé', 'accessoires-bebe', (select id from categories where slug = 'bebe-enfants'), 5, true, true),
  ('Articles scolaires', 'articles-scolaires', (select id from categories where slug = 'bebe-enfants'), 6, true, true),
  ('Sécurité enfant', 'securite-enfant', (select id from categories where slug = 'bebe-enfants'), 7, true, true),
  ('Fitness & Musculation', 'fitness-musculation', (select id from categories where slug = 'sport-loisirs'), 1, true, true),
  ('Running', 'running', (select id from categories where slug = 'sport-loisirs'), 2, true, true),
  ('Football', 'football', (select id from categories where slug = 'sport-loisirs'), 3, true, true),
  ('Cyclisme', 'cyclisme', (select id from categories where slug = 'sport-loisirs'), 4, true, true),
  ('Sports Outdoor', 'sports-outdoor', (select id from categories where slug = 'sport-loisirs'), 5, true, true),
  ('Camping & Randonnée', 'camping-randonnee', (select id from categories where slug = 'sport-loisirs'), 6, true, true),
  ('Jeux & Loisirs', 'jeux-loisirs', (select id from categories where slug = 'sport-loisirs'), 7, true, true),
  ('Accessoires sportifs', 'accessoires-sportifs', (select id from categories where slug = 'sport-loisirs'), 8, true, true),
  ('Accessoires automobiles', 'accessoires-automobiles', (select id from categories where slug = 'auto-moto'), 1, true, true),
  ('Électronique automobile', 'electronique-automobile', (select id from categories where slug = 'auto-moto'), 2, true, true),
  ('Supports téléphone', 'supports-telephone-auto', (select id from categories where slug = 'auto-moto'), 3, true, true),
  ('Éclairage automobile', 'eclairage-automobile', (select id from categories where slug = 'auto-moto'), 4, true, true),
  ('Entretien automobile', 'entretien-automobile', (select id from categories where slug = 'auto-moto'), 5, true, true),
  ('Accessoires moto', 'accessoires-moto', (select id from categories where slug = 'auto-moto'), 6, true, true),
  ('Organisation & Rangement voiture', 'organisation-rangement-voiture', (select id from categories where slug = 'auto-moto'), 7, true, true),
  ('Lampes solaires', 'lampes-solaires', (select id from categories where slug = 'energie-solaire'), 1, true, true),
  ('Kits solaires', 'kits-solaires', (select id from categories where slug = 'energie-solaire'), 2, true, true),
  ('Caméras solaires', 'cameras-solaires-energie', (select id from categories where slug = 'energie-solaire'), 3, true, true),
  ('Power Stations', 'power-stations', (select id from categories where slug = 'energie-solaire'), 4, true, true),
  ('Batteries', 'batteries', (select id from categories where slug = 'energie-solaire'), 5, true, true),
  ('Onduleurs', 'onduleurs', (select id from categories where slug = 'energie-solaire'), 6, true, true),
  ('Accessoires solaires', 'accessoires-solaires', (select id from categories where slug = 'energie-solaire'), 7, true, true),
  ('Éclairage rechargeable', 'eclairage-rechargeable', (select id from categories where slug = 'energie-solaire'), 8, true, true),
  ('Caméras Wi-Fi', 'cameras-wi-fi', (select id from categories where slug = 'securite-surveillance'), 1, true, true),
  ('Caméras 4G', 'cameras-4g', (select id from categories where slug = 'securite-surveillance'), 2, true, true),
  ('Caméras solaires', 'cameras-solaires-surveillance', (select id from categories where slug = 'securite-surveillance'), 3, true, true),
  ('Kits vidéosurveillance', 'kits-videosurveillance', (select id from categories where slug = 'securite-surveillance'), 4, true, true),
  ('Alarmes', 'alarmes', (select id from categories where slug = 'securite-surveillance'), 5, true, true),
  ('Serrures intelligentes', 'serrures-intelligentes', (select id from categories where slug = 'securite-surveillance'), 6, true, true),
  ('Détecteurs', 'detecteurs', (select id from categories where slug = 'securite-surveillance'), 7, true, true),
  ('Accessoires CCTV', 'accessoires-cctv', (select id from categories where slug = 'securite-surveillance'), 8, true, true),
  ('Consoles', 'consoles', (select id from categories where slug = 'gaming'), 1, true, true),
  ('Manettes', 'manettes', (select id from categories where slug = 'gaming'), 2, true, true),
  ('Casques Gaming', 'casques-gaming', (select id from categories where slug = 'gaming'), 3, true, true),
  ('Claviers Gaming', 'claviers-gaming', (select id from categories where slug = 'gaming'), 4, true, true),
  ('Souris Gaming', 'souris-gaming', (select id from categories where slug = 'gaming'), 5, true, true),
  ('Tapis de souris', 'tapis-de-souris', (select id from categories where slug = 'gaming'), 6, true, true),
  ('Accessoires Gaming', 'accessoires-gaming', (select id from categories where slug = 'gaming'), 7, true, true),
  ('Éclairage Gaming', 'eclairage-gaming', (select id from categories where slug = 'gaming'), 8, true, true),
  ('Outils électriques', 'outils-electriques', (select id from categories where slug = 'bricolage-outils'), 1, true, true),
  ('Outils manuels', 'outils-manuels', (select id from categories where slug = 'bricolage-outils'), 2, true, true),
  ('Mesure & Précision', 'mesure-precision', (select id from categories where slug = 'bricolage-outils'), 3, true, true),
  ('Électricité', 'electricite', (select id from categories where slug = 'bricolage-outils'), 4, true, true),
  ('Plomberie', 'plomberie', (select id from categories where slug = 'bricolage-outils'), 5, true, true),
  ('Accessoires & Consommables', 'accessoires-consommables', (select id from categories where slug = 'bricolage-outils'), 6, true, true),
  ('Équipement professionnel', 'equipement-professionnel', (select id from categories where slug = 'bricolage-outils'), 7, true, true)
on conflict (slug) do update set name = excluded.name, category_id = excluded.category_id, sort_order = excluded.sort_order, is_active = true, is_visible = true;
