-- =========================================================================
-- SENDUU — Icônes catégories/sous-catégories
-- Attribue une icône (emoji) à chaque catégorie et sous-catégorie de la
-- taxonomie réelle. Retire aussi une sous-catégorie fantôme
-- ("Supports téléphone auto" / supports-telephone-auto-auto-moto) restée
-- après le nettoyage de doublons de la migration 0009.
-- =========================================================================

delete from subcategories where slug = 'supports-telephone-auto-auto-moto';

update categories set icon = case slug
  when 'telephones-high-tech' then '📱'
  when 'informatique' then '💻'
  when 'maison-cuisine' then '🏠'
  when 'mode-accessoires' then '👗'
  when 'beaute-soins' then '💄'
  when 'bebe-enfants' then '🧸'
  when 'sport-loisirs' then '⚽'
  when 'auto-moto' then '🚗'
  when 'energie-solaire' then '☀️'
  when 'securite-surveillance' then '📷'
  when 'gaming' then '🎮'
  when 'bricolage-outils' then '🔧'
  when 'offres-promotions' then '🏷️'
end where slug in ('telephones-high-tech','informatique','maison-cuisine','mode-accessoires','beaute-soins','bebe-enfants','sport-loisirs','auto-moto','energie-solaire','securite-surveillance','gaming','bricolage-outils','offres-promotions');

update subcategories set icon = case slug
  when 'smartphones' then '📱'
  when 'telephones-reconditionnes' then '♻️'
  when 'accessoires-telephone' then '🔌'
  when 'ecouteurs-casques' then '🎧'
  when 'enceintes-bluetooth' then '🔊'
  when 'montres-connectees' then '⌚'
  when 'chargeurs-cables' then '🔋'
  when 'power-banks' then '🔋'
  when 'supports-telephone' then '📎'
  when 'gadgets-electroniques' then '✨'
  when 'ordinateurs-portables' then '💻'
  when 'pc-2-en-1' then '💻'
  when 'ordinateurs-de-bureau' then '🖥️'
  when 'tablettes' then '📱'
  when 'claviers-souris' then '⌨️'
  when 'ssd-hdd-stockage' then '💾'
  when 'cles-usb' then '💾'
  when 'adaptateurs-hub-usb' then '🔌'
  when 'accessoires-pc' then '🖱️'
  when 'reseaux-wi-fi' then '📶'
  when 'imprimantes-consommables' then '🖨️'
  when 'rangement-organisation' then '🗄️'
  when 'cuisine' then '🍳'
  when 'ustensiles-de-cuisine' then '🍴'
  when 'eclairage' then '💡'
  when 'decoration' then '🖼️'
  when 'nettoyage-entretien' then '🧹'
  when 'salle-de-bain' then '🛁'
  when 'articles-pour-la-maison' then '🏡'
  when 'gadgets-maison' then '🧰'
  when 'refrigerateurs' then '🧊'
  when 'vetements-homme' then '👔'
  when 'vetements-femme' then '👗'
  when 'chaussures' then '👟'
  when 'sacs' then '👜'
  when 'montres' then '⌚'
  when 'bijoux-accessoires' then '💍'
  when 'lunettes' then '🕶️'
  when 'accessoires-de-mode' then '🧣'
  when 'soins-du-visage' then '🧴'
  when 'soins-du-corps' then '🧴'
  when 'accessoires-beaute' then '💅'
  when 'coiffure' then '💇'
  when 'manucure-pedicure' then '💅'
  when 'parfums' then '🧴'
  when 'miroirs-accessoires' then '🪞'
  when 'vetements-bebe' then '👶'
  when 'chaussures-enfants' then '👟'
  when 'jouets' then '🧸'
  when 'eveil-education' then '🧩'
  when 'accessoires-bebe' then '🍼'
  when 'articles-scolaires' then '🎒'
  when 'securite-enfant' then '🛡️'
  when 'fitness-musculation' then '🏋️'
  when 'running' then '🏃'
  when 'football' then '⚽'
  when 'cyclisme' then '🚴'
  when 'sports-outdoor' then '🏕️'
  when 'camping-randonnee' then '⛺'
  when 'jeux-loisirs' then '🎲'
  when 'accessoires-sportifs' then '🏅'
  when 'accessoires-automobiles' then '🚗'
  when 'electronique-automobile' then '🔋'
  when 'supports-telephone-auto' then '📎'
  when 'eclairage-automobile' then '💡'
  when 'entretien-automobile' then '🧴'
  when 'accessoires-moto' then '🏍️'
  when 'organisation-rangement-voiture' then '🧰'
  when 'lampes-solaires' then '🔆'
  when 'kits-solaires' then '☀️'
  when 'cameras-solaires-energie' then '📷'
  when 'power-stations' then '🔋'
  when 'batteries' then '🔋'
  when 'onduleurs' then '⚡'
  when 'accessoires-solaires' then '🔌'
  when 'eclairage-rechargeable' then '💡'
  when 'cameras-wi-fi' then '📷'
  when 'cameras-4g' then '📷'
  when 'cameras-solaires-surveillance' then '📷'
  when 'kits-videosurveillance' then '🎥'
  when 'alarmes' then '🚨'
  when 'serrures-intelligentes' then '🔐'
  when 'detecteurs' then '🚨'
  when 'accessoires-cctv' then '🔧'
  when 'consoles' then '🎮'
  when 'manettes' then '🎮'
  when 'casques-gaming' then '🎧'
  when 'claviers-gaming' then '⌨️'
  when 'souris-gaming' then '🖱️'
  when 'tapis-de-souris' then '🖱️'
  when 'accessoires-gaming' then '🕹️'
  when 'eclairage-gaming' then '💡'
  when 'outils-electriques' then '🔌'
  when 'outils-manuels' then '🔧'
  when 'mesure-precision' then '📏'
  when 'electricite' then '⚡'
  when 'plomberie' then '🔧'
  when 'accessoires-consommables' then '🧰'
  when 'equipement-professionnel' then '🦺'
end where slug in ('smartphones','telephones-reconditionnes','accessoires-telephone','ecouteurs-casques','enceintes-bluetooth','montres-connectees','chargeurs-cables','power-banks','supports-telephone','gadgets-electroniques','ordinateurs-portables','pc-2-en-1','ordinateurs-de-bureau','tablettes','claviers-souris','ssd-hdd-stockage','cles-usb','adaptateurs-hub-usb','accessoires-pc','reseaux-wi-fi','imprimantes-consommables','rangement-organisation','cuisine','ustensiles-de-cuisine','eclairage','decoration','nettoyage-entretien','salle-de-bain','articles-pour-la-maison','gadgets-maison','refrigerateurs','vetements-homme','vetements-femme','chaussures','sacs','montres','bijoux-accessoires','lunettes','accessoires-de-mode','soins-du-visage','soins-du-corps','accessoires-beaute','coiffure','manucure-pedicure','parfums','miroirs-accessoires','vetements-bebe','chaussures-enfants','jouets','eveil-education','accessoires-bebe','articles-scolaires','securite-enfant','fitness-musculation','running','football','cyclisme','sports-outdoor','camping-randonnee','jeux-loisirs','accessoires-sportifs','accessoires-automobiles','electronique-automobile','supports-telephone-auto','eclairage-automobile','entretien-automobile','accessoires-moto','organisation-rangement-voiture','lampes-solaires','kits-solaires','cameras-solaires-energie','power-stations','batteries','onduleurs','accessoires-solaires','eclairage-rechargeable','cameras-wi-fi','cameras-4g','cameras-solaires-surveillance','kits-videosurveillance','alarmes','serrures-intelligentes','detecteurs','accessoires-cctv','consoles','manettes','casques-gaming','claviers-gaming','souris-gaming','tapis-de-souris','accessoires-gaming','eclairage-gaming','outils-electriques','outils-manuels','mesure-precision','electricite','plomberie','accessoires-consommables','equipement-professionnel');
